# Generated by Django 4.2.23 on 2025-08-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='last_name',
        ),
    ]
